

package org.tigris.scarab.om;


import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.om.Persistent;

/** 
 * This class manages WorkflowTransitionAction objects.  
 * The skeleton for this class was autogenerated by Torque  * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public class WorkflowTransitionActionManager
    extends BaseWorkflowTransitionActionManager
{
    /**
     * Creates a new <code>WorkflowTransitionActionManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public WorkflowTransitionActionManager()
        throws TorqueException
    {
        super();
    }

}





