/*
 * b19->b20 Migration.
 *
 * Workflow migration
 *
 * Create the new table that defines the transitions between diferent values of a
 * dropdown list attribute.
 */
CREATE TABLE SCARAB_TRANSITION
(
                            TRANSITION_ID INTEGER NOT NULL,
                            ROLE_ID INTEGER,
                            ATTRIBUTE_ID INTEGER NOT NULL,
                            FROM_OPTION_ID INTEGER,
                            TO_OPTION_ID INTEGER,
                            DISABLED_IF_BLOCKED INTEGER (1),                            
    PRIMARY KEY(TRANSITION_ID),
    FOREIGN KEY (ATTRIBUTE_ID) REFERENCES SCARAB_ATTRIBUTE (ATTRIBUTE_ID),
    FOREIGN KEY (FROM_OPTION_ID) REFERENCES SCARAB_ATTRIBUTE_OPTION (OPTION_ID),
    FOREIGN KEY (TO_OPTION_ID) REFERENCES SCARAB_ATTRIBUTE_OPTION (OPTION_ID)
);

CREATE TABLE SCARAB_CONDITION
(
    CONDITION_ID INTEGER NOT NULL,
    TRANSITION_ID INTEGER,
    MODULE_ID INTEGER,
    ISSUE_TYPE_ID INTEGER,
    ATTRIBUTE_ID INTEGER,
    OPTION_ID INTEGER NOT NULL,
    PRIMARY KEY(CONDITION_ID),
    FOREIGN KEY (MODULE_ID, ATTRIBUTE_ID, ISSUE_TYPE_ID)
    REFERENCES SCARAB_R_MODULE_ATTRIBUTE
        (MODULE_ID, ATTRIBUTE_ID, ISSUE_TYPE_ID),
    FOREIGN KEY (TRANSITION_ID)
        REFERENCES SCARAB_TRANSITION (TRANSITION_ID),
    FOREIGN KEY (ATTRIBUTE_ID)
        REFERENCES SCARAB_ATTRIBUTE (ATTRIBUTE_ID),
    FOREIGN KEY (OPTION_ID)
        REFERENCES SCARAB_ATTRIBUTE_OPTION (OPTION_ID)
);
